=== osvalr/avgust/Desarrollo/Tools/GeneradorModel/V2/Sources/GeneratorQueryMyBatis/src/main/resources/Query.xsd
<?xml version="1.0"?>
<!-- To change this license header, choose License Headers in Project Properties. 
	To change this template file, choose Tools | Templates and open the template 
	in the editor. -->

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.sakerk.com.pe/query/generator/mybatis"
	xmlns:xsd="http://www.sakerk.com.pe/query/generator/mybatis"
	elementFormDefault="qualified">

	<complexType name="Target">
		<sequence>
			<element type="string" name="targetPackage" />
			<element type="string" name="targetProject" />
			<element type="string" name="type" />
		</sequence>
	</complexType>

	<complexType name="Targets">
		<sequence>
			<element name="target" type="xsd:Target" maxOccurs="3" minOccurs="3" />
		</sequence>
	</complexType>

	<complexType name="Query">
		<sequence>
			<element type="string" name="name" />
			<element type="boolean" name="generate" />
			<element type="string" name="sql" />
		</sequence>
	</complexType>

	<complexType name="Querys">
		<sequence>
			<element name="query" type="xsd:Query" maxOccurs="unbounded" minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="QueryGenerator">
		<sequence>
			<element name="configs" type="xsd:Targets" maxOccurs="1" minOccurs="1" />
			<element name="querys" type="xsd:Querys" maxOccurs="1" minOccurs="1" />
		</sequence>
	</complexType>

	<element name="queryGenerator" type="xsd:QueryGenerator" />

</schema>

=== osvalr/avgust/Desarrollo/Tools/GeneradorModel/V2/Sources/GeneratorQueryMyBatis/src/main/resources/Query.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryGenerator xmlns="http://www.sakerk.com.pe/query/generator/mybatis" 
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
					xsi:schemaLocation="http://www.sakerk.com.pe/query/generator/mybatis Query.xsd ">
  <configs>
    
	    <target>
	      <targetPackage>pe.com.focus.sakerk.repository.custom.model</targetPackage>
<!--  		  <targetProject>/Users/JRaffo/GitHub/FocusConsultoresSAC/sakerkapp/Developement/SakerkApp/SakerkRepositoryApp/src/main/java</targetProject> -->
	      <targetProject>C:\GITHUB/focuslabs/Generales/Developement/FocusRepositoryMybatisApp/src/main/java</targetProject>
	      <type>javaModelGenerator</type>
	    </target>
	   
	    <target>
	      <targetPackage>pe.com.focus.sakerk.repository.custom.mapper</targetPackage>
<!-- 	      <targetProject>/Users/JRaffo/GitHub/FocusConsultoresSAC/sakerkapp/Developement/SakerkApp/SakerkRepositoryApp/src/main/resources</targetProject> -->
	      <targetProject>C:/GITHUB/focuslabs/Generales/Developement/FocusRepositoryMybatisApp/src/main/resources</targetProject>
	      <type>sqlMapGenerator</type>
	    </target>
	    
	    <target>
	      <targetPackage>pe.com.focus.sakerk.repository.custom.mapper</targetPackage>
<!-- 	      <targetProject>/Users/JRaffo/GitHub/FocusConsultoresSAC/sakerkapp/Developement/SakerkApp/SakerkRepositoryApp/src/main/java</targetProject> -->
	      <targetProject>C:/GITHUB/focuslabs/Generales/Developement/FocusRepositoryMybatisApp/src/main/java</targetProject>
	      <type>javaClientGenerator</type>
	    </target>
	    
    
  </configs>
    
  <querys>
     
	   <query>
	      <name>EstadoQuery</name>
	      <generate>true</generate>
	      <sql>
	      <![CDATA[
	      
	      select 
	      @
			et.srl_id_estado_tabla #INTEGER,
			det.srl_id_detalle_estado_tabla #INTEGER,
			det.var_cod_estado,
			det.var_nombre_estado,
			det.tsp_fecha_registro #DATE
		  @ 
			from sernanp.t_estado_tabla et
			inner join sernanp.t_detalle_estado_tabla det
			on et.srl_id_estado_tabla = det.srl_id_estado_tabla
			where
			@
			et.var_nombre_tabla = #{var_nombre_tabla & #STRING} 
			@
			
		  ]]>
	      </sql>
	    </query>

	    

  </querys>
  
</queryGenerator>
